## spring security 配置
security:
  oauth2:
    client:
      ignore-urls:
        - /webjars/**
        - /v3/api-docs/**
        - /doc.html
        - /swagger-resources
        - /token/check_token
        - /error
        - /druid/**
        - /actuator/**
        - /code/**
        - /policy/**
        - /enums/**
# 前端密码登录解密密钥
gateway:
  encodeKey: pigxpigxpigxpigx

# 数据源
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 9  #避免和微服务 PIGX 冲突
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#      url: jdbc:mysql://61.177.172.93:63306/pigxx_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
#      stat-view-servlet:
#        enabled: true
#        allow: ""
#        url-pattern: /druid/*
#      filter:
#        stat:
#          enabled: true
#          log-slow-sql: true
#          slow-sql-millis: 10000
#          merge-sql: false
#        wall:
#          config:
#            multi-statement-allow: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pigxx_boot?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 本地文件系统
file:
  local:
    enable: true
    basePath: /data/file

# Logger Config
logging:
  level:
    com.pig4cloud.pigx.admin.mapper: debug

# 租户表维护
pigx:
  tenant:
    column: tenant_id
    tables:
      - sys_user
      - sys_role
      - sys_menu
      - sys_dept
      - sys_log
      - sys_social_details
      - sys_dict
      - sys_dict_item
      - sys_public_param
      - sys_log
      - sys_file
      - sys_oauth_client_details
      - sys_post